### ISSUE TITLE
アクセスできない…

### ISSUE THREAD

**Issue by 216nonon** [shierote/mates_issues#43]
![image](https://user-images.githubusercontent.com/54049156/63634345-f421f580-c68f-11e9-91ce-93b759339198.png)
アクセスできなくなっている。（2019/8/24現在）

エラーメッセージ
```
このサイトにアクセスできません mates-dp9.site からの応答時間が長すぎます。
次をお試しください

接続を確認する
プロキシとファイアウォールを確認する
ERR_CONNECTION_TIMED_OUT
```

**Comment by a1r3us** [comment]
レンタルサーバーの支払い関係の問題だった
